default:
  spark.app.name: MyApp
  spark.master: yarn-client
  spark.home: /opt/mapr/spark/spark-2.0.0-bin-2.2.0
  spark.version: 2.0.0
  spark.yarn.queue: development
  spark.executor.instances: 4
  spark.executor.cores: 2
  spark.executor.memory: 4g

spark-1.6:
  spark.home: /opt/mapr/spark/spark-1.6.1
  spark.version: 1.6.1

acceptance:
  spark.yarn.queue: acceptance

production:
  spark.yarn.queue: production
